version: "3.8"
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: gigi
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - '3308:3036'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:

