version: "3.8"
services:
  db:
    image: mysql
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    ports:
      - 42333:3306
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:
